<?php
/**
 * Email notifications Response handler
 *
 * Adds Email notifications for forms
 *
 * @author  awesome.ug, Author <support@awesome.ug>
 * @package Questions/Restrictions
 * @version 1.0.0
 * @since   1.0.0
 * @license GPL 2
 *
 * Copyright 2015 awesome.ug (support@awesome.ug)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2, as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

if( !defined( 'ABSPATH' ) ){
	exit;
}

class Questions_EmailNotifications extends  Questions_ResponseHandler{

	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->title = __( 'Email Notifications', 'wcsc-locale' );
		$this->slug = 'emailnotifications';

		add_action( 'admin_print_styles', array( __CLASS__, 'enqueue_admin_styles' ) );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_admin_scripts' ) );

		add_action( 'wp_ajax_get_email_notification_html', array( __CLASS__, 'ajax_get_email_notification_html' ) );

		// used to capture javascript settings generated by the editor
		add_filter( 'tiny_mce_before_init', 'Quesions_WPEditorBox::tiny_mce_before_init', 10, 2 );
		add_filter( 'quicktags_settings', 'Quesions_WPEditorBox::quicktags_settings', 10, 2 );
	}

	/**
	 * Handles the data after user submitted the form
	 * @param $response_id
	 * @param $response
	 */
	public function handle( $response_id, $response ){
	}

	public function option_content(){

		$html = '<div id="questions-email-notifications">';
			$html.= '<div class="list">';

					$notifications = array( 1, 2, 3 );

					$html.= '<div class="notifications widget-title">';

					foreach( $notifications AS $notification ){
						$notification_name = '';
						$notification_from_name = '';
						$notification_from_email = '';
						$notification_to_email = '';
						$notification_subject = '';
						$notification_message = '';
						$html.= self::get_notification_settings_html( $notification, $notification_name, $notification_from_name, $notification_from_email, $notification_to_email, $notification_subject, $notification_message );
					}

				$html.= '</div>';
			$html.= '</div>';
			$html.= '<div class="actions">';
			$html.= '<input id="questions_add_email_notification" type="button" value="' . esc_attr( 'Add Notification', 'questions-locale' ) . '" class="button" />';
			$html.= '</div>';
		$html.= '</div>';
		$html.= '<div class="clear"></div>';

		return $html;
	}

	/**
	 * Getting HTML for notification
	 *
	 * @param $notification_name
	 * @param $notification_from_name
	 * @param $notification_from_email
	 * @param $notification_to_email
	 * @param $notification_subject
	 * @param $notification_message
	 *
	 * @return string $html
	 */
	public static function get_notification_settings_html( $id, $notification_name = '', $notification_from_name = '', $notification_from_email = '', $notification_to_email = '', $notification_subject = '', $notification_message = '' ){

		ob_start();
		wp_editor( $notification_message, 'email_notification_text_' . $id );
		$editor = ob_get_clean();

		$html = '<h4 class="widget-top">' . esc_attr( 'Name', 'questions-locale' ) . '</h4>';
		$html.= '<div class="notification widget-inside">';
			$html.= '<table class="form-table">';
				$html.= '<tr>';
					$html.= '<th><label for="email_notification_name">' . esc_attr( 'Notification Name', 'questions-locale' ) . '</label></th>';
					$html.= '<td><input type="text" name="email_notification_to" value="' . $notification_name . '"></td>';
				$html.= '</tr>';
				$html.= '<tr>';
					$html.= '<th><label for="email_notification_from_name">' . esc_attr( 'From Name', 'questions-locale' ) . '</label></th>';
					$html.= '<td><input type="text" name="email_notification_from_name" value="' . $notification_from_name . '"></td>';
				$html.= '</tr>';
				$html.= '<tr>';
					$html.= '<th><label for="email_notification_from_email">' . esc_attr( 'From Email', 'questions-locale' ) . '</label></th>';
					$html.= '<td><input type="text" name="email_notification_from_email" value="' . $notification_from_email . '"></td>';
				$html.= '</tr>';
				$html.= '<tr>';
					$html.= '<th><label for="email_notification_to_email">' . esc_attr( 'To Email', 'questions-locale' ) . '</label></th>';
					$html.= '<td><input type="text" name="email_notification_to_email" value="' . $notification_to_email . '"></td>';
				$html.= '</tr>';
				$html.= '<tr>';
					$html.= '<th><label for="email_notification_subject">' . esc_attr( 'Subject', 'questions-locale' ) . '</label></th>';
					$html.= '<td><input type="text" name="email_notification_subject" value="' . $notification_subject . '"></td>';
				$html.= '</tr>';
				$html.= '<tr>';
					$html.= '<th><label for="email_notification_message">' . esc_attr( 'Message', 'questions-locale' ) . '</label></th>';
					$html.= '<td>' . $editor . '</td>';
				$html.= '</tr>';
			$html.= '</table>';
		$html.= '</div>';

		return $html;
	}

	/**
	 * Get Email notification HTML
	 */
	public static function ajax_get_email_notification_html(){
		$id = time();

		$html = self::get_notification_settings_html( $id );
		$editor_id = 'email_notification_text_' . $id;

		$mce_init = Quesions_WPEditorBox::get_mce_init( $editor_id );
		$qt_init = Quesions_WPEditorBox::get_qt_init( $editor_id );

		$html.= '<script type="text/javascript">
			tinyMCEPreInit.mceInit = jQuery.extend( tinyMCEPreInit.mceInit, ' . $mce_init . ' );
            tinyMCEPreInit.qtInit = jQuery.extend( tinyMCEPreInit.qtInit, ' . $qt_init . ' );
            console.log( tinyMCEPreInit.qtInit["' . $editor_id . '"] );

            tinyMCE.init( tinyMCEPreInit.mceInit["' . $editor_id . '"] );
            try { quicktags( tinyMCEPreInit.qtInit["' . $editor_id . '"] ); } catch(e){ console.log( e )}
        </script>';

		echo $html;
		die();
	}



	/**
	 * Enqueue admin scripts
	 */
	public static function enqueue_admin_scripts()
	{
		wp_enqueue_script( 'jquery-ui-accordion' );
		wp_enqueue_script( 'questions-response-handlers-email-notification', QUESTIONS_URLPATH . '/components/response-handlers/base-response-handlers/includes/js/email-notifications.js' );
	}

	/**
	 * Enqueue admin styles
	 */
	public static function enqueue_admin_styles()
	{
		wp_enqueue_style( 'questions-response-handlers-email-notification', QUESTIONS_URLPATH . '/components/response-handlers/base-response-handlers/includes/css/email-notifications.css' );
	}
}
qu_register_response_handler( 'Questions_EmailNotifications' );